apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-svc.yaml
  - frontend-deployment.yaml
  - frontend-svc.yaml
  - HPA-backend.yaml
  - HPA-frontend.yaml
  - ingress.yaml

images:
  - name: cloudwithyash/shopverse-back
    newTag: ddcc56f6922b5dc530bc529c60f06e0a48d1c235
  - name: cloudwithyash/shopverse-front
    newTag: ddcc56f6922b5dc530bc529c60f06e0a48d1c235
