apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - backend-deployment.yaml
  - backend-svc.yaml
  - frontend-deployment.yaml
  - frontend-svc.yaml
  - HPA-backend.yaml
  - HPA-frontend.yaml
  - ingress.yaml