apiVersion: v1
kind: Secret
metadata:
  name: shopverse-secret
  namespace: shopverse

type: Opaque

stringData:
  DB_HOST: "project-mysql.c8h42c62i6lr.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "shopverse"
  DB_USER: "admin"
  DB_PASSWORD: "StrongPassword123!"