apiVersion: v1
kind: Secret
metadata:
  name: shopverse-secret
  namespace: shopverse

type: Opaque

stringData:
  DB_HOST: "placeholder"
  DB_PORT: "3306"
  DB_NAME: "placeholder"
  DB_USER: "admin"
  DB_PASSWORD: "placeholder"